# check speedup, slow of startup, del unneeded
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

# del ugly icons
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_LOCK_ICON='read only'
POWERLEVEL9K_PYTHON_ICON=''
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_BRANCH_ICON=''
POWERLEVEL9K_VCS_UNSTAGED_ICON='⎢ unstaged'
POWERLEVEL9K_VCS_UNTRACKED_ICON='⎢ untracked'
POWERLEVEL9K_VCS_STASH_ICON='⎢ stashes '
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⎢ ⬇ '
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⎢ ⬆ '
POWERLEVEL9K_VCS_STAGED_ICON='⎢ staged'
POWERLEVEL9K_VCS_TAG_ICON='⎢ tag '

DEFAULT_USER='tandav'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''

POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='$ '
# POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='ॐ '

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
