# this theme can work in Terminal.app without any problems
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs virtualenv anaconda) # check speedup, slow of startup, del unneeded
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

# truncate dir path
# POWERLEVEL9K_SHORTEN_STRATEGY='truncate_middle'
# POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

# del ugly icons
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_LOCK_ICON='read only'
POWERLEVEL9K_PYTHON_ICON=''
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_BRANCH_ICON=''
POWERLEVEL9K_VCS_UNSTAGED_ICON='⎢unstaged'
POWERLEVEL9K_VCS_UNTRACKED_ICON='⎢untracked'
POWERLEVEL9K_VCS_STASH_ICON='⎢stashes '
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⎢⬇'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⎢⬆ '
POWERLEVEL9K_VCS_STAGED_ICON='⎢staged'
POWERLEVEL9K_VCS_TAG_ICON='⎢tag '

DEFAULT_USER='tandav'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='$ '

# before: |  >  >  >       <  |  (dislike)
#  after: |  |  |  |       |  |  (like)
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''

# virtualenv style
POWERLEVEL9K_ANACONDA_LEFT_DELIMITER=''
POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=''
POWERLEVEL9K_ANACONDA_BACKGROUND='red'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='red'

# TODO fix colors
# POWERLEVEL9K_VCS_CLEAN_FOREGROUND='blue'
# POWERLEVEL9K_VCS_CLEAN_BACKGROUND='black'
# POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
# POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='black'
# POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='red'
# POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='black'
