#!/data/data/com.termux/files/usr/bin/python
import sys
import shlex
import subprocess
url = sys.argv[1]


repo = '/data/data/com.termux/files/home/storage/downloads/projects/knowledge_private'
file = 'android-notes.md'

with open(file, 'a') as f:
    print('- URL:', url, file=f)

subprocess.run(shlex.split(f'git add {file}'), cwd=repo)
subprocess.run(shlex.split(f'git commit -m "add notes from android"'), cwd=repo)
subprocess.run(shlex.split(f'git push'), cwd=repo)
